from random import choice
paises = [
    "Andorra",
    "Emiratos Árabes Unidos",
    "Afganistán",
    "Antigua y Barbuda",
    "Anguila",
    "Albania",
    "Armenia",
    "Antillas Holandesas",
    "Angola",
    "Antártida",
    "Argentina",
    "Samoa Americana",
    "Austria",
    "Australia",
    "Aruba",
    "Azerbaiyán",
    "Bosnia y Herzegovina",
    "Barbados",
    "Bangladesh",
    "Bélgica",
    "Burkina Faso",
    "Bahrein",
    "Burundi",
    "Benin",
    "Bermudas",
    "Bolivia",
    "Brasil",
    "Bahamas",
    "Bután",
    "Isla Bouvet",
    "Bulgaria",
    "Botswana",
    "Brunei",
    "Bielorrusia",
    "Belice",
    "Canadá",
    "República Centroafricana",
    "Congo",
    "Suiza",
    "Costa de Marfil",
    "Islas Cook",
    "Chile",
    "Camerún",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Isla de Navidad",
    "Chipre",
    "República Checa",
    "Alemania",
    "Djibouti",
    "Dinamarca",
    "Dominica",
    "República Dominicana",
    "Argelia",
    "Ecuador",
    "Estonia",
    "Egipto",
    "Sáhara Occidental",
    "Eritrea",
    "España",
    "Etiopía",
    "Finlandia",
    "Fiji",
    "Islas Malvinas",
    "Micronesia",
    "Islas Feroe",
    "Francia",
    "Gabón",
    "Reino Unido",
    "Granada",
    "Georgia",
    "Guayana Francesa",
    "Ghana",
    "Gibraltar",
    "Groenlandia",
    "Gambia",
    "Guinea",
    "Guadalupe",
    "Guinea Ecuatorial",
    "Grecia",
    "Georgia del Sur y Islas Sandwich del Sur",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guayana",
    "Hong Kong",
    "Islas Heard y McDonald",
    "Honduras",
    "Croacia",
    "Haití",
    "Hungría",
    "Indonesia",
    "Irlanda",
    "Israel",
    "India",
    "Territorio Británico del Océano Índico", 
    "Irak",
    "Irán",
    "Islandia",
    "Italia",
    "Jamaica",
    "Jordania",
    "Japón",
    "Kenia",
    "Kirguistán",
    "Camboya",
    "Kiribati",
    "Comoras",
    "Saint Kitts y Nevis",
    "Corea del Norte",
    "Corea del Sur",
    "Kuwait",
    "Las Islas Caimán",
    "Kazajstán",
    "Laos",
    "Líbano",
    "Santa Lucía",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesoto",
    "Lituania",
    "Luxemburgo",
    "Letonia",
    "Libia",
    "Marruecos",
    "Mónaco",
    "Moldavia",
    "Madagascar",
    "Islas Marshall",
    "Macedonia",
    "Malí",
    "Myanmar",
    "Mongolia",
    "Macao",
    "Islas Marianas del Norte",
    "Martinica",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauricio",
    "Maldivas",
    "Malawi",
    "México",
    "Malasia",
    "Mozambique",
    "Namibia",
    "Nueva Caledonia",
    "Níger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Países Bajos",
    "Noruega",
    "Nepal",
    "Nauru",
    "Niue",
    "Nueva Zelanda",
    "Omán",
    "Panamá",
    "Perú",
    "Polinesia francés",
    "Papua Nueva Guinea",
    "Filipinas",
    "Pakistán",
    "Polonia",
    "San Pedro y Miquelón",
    "Pitcairn",
    "Puerto Rico",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Reunión",
    "Rumania",
    "La Federación de Rusia",
    "Ruanda",
    "Arabia Saudita",
    "Las Islas Salomón",
    "Seychelles",
    "Sudán",
    "Suecia",
    "Singapur",
    "Santa Elena",
    "Eslovenia",
    "Svalbard y Jan Mayen",
    "República Eslovaca",
    "Sierra Leona",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "Santo Tomé y Príncipe",
    "El Salvador",
    "Siria",
    "Swazilandia",
    "Islas Turcas y Caicos",
    "Chad",
    "Territorios del sur francés",
    "Togo",
    "Tailandia",
    "Tayikistán",
    "Tokelau",
    "Turkmenistán",
    "Túnez",
    "Tonga",
    "Timor Oriental",
    "Turquía",
    "Trinidad y Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania",
    "Ucrania",
    "Uganda",
    "Reino Unido",
    "Islas menores de EE.UU.",
    "Estados Unidos de América",
    "Uruguay",
    "Uzbekistán",
    "Ciudad del Vaticano",
    "San Vicente y las Granadinas",
    "Venezuela",
    "Islas Vírgenes",
    "Vietnam",
    "Vanuatu",
    "Islas Wallis y Futuna",
    "Samoa",
    "Yemen",
    "Mayotte",
    "Yugoslavia",
    "Sudáfrica",
    "Zambia",
    "Zaire",
    "Zimbabue"
]

nombres = [
    "Carlos Marx",
    "Adam Smith",
    "Francisco Franco",
    "Nieto Alcala-Zamora",
    "Manuel Azaña",
    "Sabino Arana",
    "Joaquin Sabrina",
    "Rafa Nadal",
    "Monserrat Caballe",
    "Freddy Mercury",
    "Godofredo Bezos",
    "Amancio Ortega",
    "Ortega y Gasset",
    "Ramon y Cajal",
    "Ash Kempchum",
    "Sans",
    "Gadafi",
    "Bin Ladden",
    "Largo Caballero",
    "Teemo",
    "Colon",
    "Blas de Lezo",
    "Isabel Diaz Ayuso",
    "Puigdemont",
    "Perro Sanxe",
    "Mateo Salvini",
    "Jose Antonio Primo de Rivera",
    "Miguel Primo de Rivera",
    "Emilo Mola",
    "Jose Antonio, primo de Albert Rivera,",
    "Juan Carlos I",
    "Felipe VI",
    "Felipe V",
    "Carlos II",
    "Rafael Alberti",
    "Antonio Machado",
    "Salvador Dali",
    "Carmen Polo",
    "Froilan",
    "Día Sexto",
    "Lola Flores",
    "Dolores Ibárruri",
    "Clara Ponsati",
    "Clara Campoamor",
    "Esperanza Aguirre",
    "Carmen Calvo",
    "Nadia Calviño",
    "Dalas Review",
    "Ibai",
    "Vegetta777",
    "Mayichi",
    "Orslok",
    "Extremoduro",
    "Taburete",
    "Estopa",
    "La oreja de Van Gogh",
    "José Stalin",
    "Adolfo Hitler",
    "Vladimirio Lenin",
    "Benito Mussolini",
    "La Pegatina",
    "Rosalia",
    "Rosalia de Castro",
    "Julio Cesar",
    "Cleopatra",
    "Echinque",
    "Santiago Abascal",
    "Toni Cantó",
    "Jose Maria Aznar",
    "Blas Cantó",
    "Felipe Gonzalez",
    "Nicolas Maduro",
    "Carrero Blanco",
    "OOM-32",
    "pirx_pilot88",
    "Erkadia",
    "DGKeeper",
    "tercio-de-flandes",
    "jb-trek",
    "BasadoBot",
    "Pablo Iglesias Posse",
    "El Coletas",
    "Charmander",
    "Pablo Casado",
    "Irene Montero",
    "Hannah Montana",
    "Katy Perry",
    "Perry el ornitorrinco",
    "La CUP", 
    "Anatoli Karpov",
    "Magnus Carlsen",
    "Garry Kasparov",
    "David, el niño Antón,",
    "Jordi el niño polla",
    "David el gnomo",
    "Papa pitufo",
    "Gargamel",
    "D'Artagnan, el aprendiz de los tres mosqueteros,",
    "Gabriel Garcia Marquez",
    "Juan Magan",
    "Luis Fonsi",
    "Camilo Sexto",
    "Jean Jungkook",
    "Aristóteles",
    "Gengis Kan",
    "Leonardo da Vinci",
    "Miguel de Cervantes",
    "Simón Bolívar",
    "Ana Frank",
    "Elon Musk",
    "PewDiePie",
    "Donald Trump",
    "Joe Biden",
    "Tracer, la de overwatch,",
    "Mercy, la de overwatch,",
    "Messi",
    "Cristiano Ronaldo",
    "Emmanuel Macron",
    "El primer ministro de la India",
    "Xi Jinping",
    "Winnie the Pooh",
    "Boris Johnson",
    "Margaret Thatcher",
    "Wiston Churchill",
    "Hirohito",
    "Camela",
    "El Albacete FC",
    "El equipo Benjamin de futbol de Granadilla de Abona, Canarias",
    "Perez-Reverte",
    "Pedro Picapiedra",
    "Elvis Presley",
    "Julio Iglesias",
    "Miguel Bosé",
    "Kim Jong Un",
    "Kim Jo Jong",
    "King Kong",
    "Joseph Joestar",
    "Fran Perea",
    "Albert Pla",
    "Paco Sanz",
    "Alejandro Sanz",
    "Melendi",
    "Bambi"
]

todasLasFrases = [
    "{nombreuser} es un valor seguro",
    "Esto con {insertarnombre} no pasaba",
    "{insertarnombre} tiene el record mundial en salto de altura",
    "{insertarnombre} tiene mil rosas para ti, {nombreuser}",
    "Sabes, yo conocí a {insertarnombre} antes de que fuera famoso",
    "{insertarnombre} se va de gira con Hatsune Miku",
    "{insertarnombre} es sus",
    "{insertarnombre} te ofrece un porro, ¿{nombreuser} aceptas?",
    "{insertarnombre} cree en la republica independiente de Murcia",
    "{insertarnombre} es pambisitxs",
    "¡Suscribete al only fans de {insertarnombre} por ₽9.99 ya mismo!",
    "{nombreuser} debe pilotar el EVA-01 o rei debera hacerlo",
    "Estas en un coma, {nombreuser}, despiertate de la matrix",
    "Slava {insertarnombre}",
    "Si lees esto eres fan de {insertarnombre}",
    "Si eres pobre es por que quieres, mira a {insertarnombre} que empezó pobre como una rata",
    "{insertarnombre} ha desertado de Ciudadanos",
    "{insertarnombre} está planteandose comprar {pais}",
    "Rápido, {nombreuser}, {insertarnombre} va a hacer un golpe de estado, ¿lo apoyas?",
    "Viva Estopa",
    "EEUU está planteandose invadir {pais}",
    "{insertarnombre} te espera con la carita empapada, {nombreuser}",
    "{insertarnombre} ha volado por los aires",
    "{nombreuser}, te has encontrado con {insertarnombre} en un botellón, ¿que haces?",
    "{pais} será la próxima colonia española",
    "{insertarnombre} es inteligente, sé como {insertarnombre}",
    "{pais} sería mejor bajo la dictadura militar de {insertarnombre}",
    "{insertarnombre} ficha por el Barça",
    "Nuestro capitan revolucionario, {insertarnombre}, ha bendecido este post",
    "{insertarnombre} piensa que la tortilla es mejor sin cebolla",
    "Venga va, acabate las lentejas que los niños de Africa se comerían hasta la cuchara",
    "{insertarnombre} se está haciendo una racha de bajas en el LOL",
    "La primera bomba norcoreana va a ir a {pais}",
    "{insertarnombre} es un antivacunas",
    "Yo conozco un sitio que te ponen mejor tapa",
    "{nombreuser} delenda est",
    "{insertarnombre} es un agente doble norcoreano",
    "{insertarnombre} ha plantado la bomba",
    "{insertarnombre} se ha unido a los vengadores",
    "{insertarnombre} piensa que la tierra es plana",
    "{insertarnombre} te espera con la carita empapada",
    "Los gallegos son la clase dominante en todo el mundo",
    "Yo conozco uno que hace lo mismo pero a mitad de precio",
    "Con un 2-5 te digo yo que llevaba al Madrid a copa",
    "Plorareu",
    "Hay que trabajar más por que menos es imposible",
    "Los impuestos son un robo, mira a {insertarnombre}",
    "Los Simpsons predijeron a {insertarnombre}",
    "¡Ayuda por favor, no soy un bot, soy un niño venezolano que está contando los basados!",
    "{nombreuser} quiere un rey llamado Karl",
    "Habemus papam, {insertarnombre}",
    "{insertarnombre} lidera la III Republica Española",
    "{nombreuser} sacame de latinoamerica, estoy cansado de {pais}",
    "{insertarnombre} está planteandose comprar {pais}",
    "{insertarnombre} es criminal de guerra",
    "Españoles, {insertarnombre} ha muerto",
    "Mmm patas",
    "Si es que con {insertarnombre} se vivia mejor",
    "{insertarnombre} te invita a una partida al LOL, ¿aceptas {nombreuser}?",
    "{nombreuser} digame su nombre, que le voy a apuntar un 0",
    "Spain is different",
    "{insertarnombre} estará en el proximo arco de jojo's",
    "Se debería hacer más rule34 de {insertarnombre}",
    "{nombreuser} tiene pornografia de {insertarnombre}",
    "{nombreuser} es nivel 107 en el LOL",
    "Me cago en la madre de {insertarnombre}",
    "El himno de España será compuesto por {insertarnombre}",
    "{insertarnombre} tiene un testiculo más grande que el otro",
    "Odio mi vida...",
    "{insertarnombre} cree que su motorola es un espia del gobierno",
    "Sí, utilizo ese pantalón",
    "No hará mucho frio ahí",
    "Que grande {insertarnombre}",
    "¿Tengo que continuar la canción?",
    "¿Tampoco pasa nada, sabes?",
    "No, no necesito calcetines",
    "Joder, esos son un montón de calcentines",
    "Muchas gracias",
    "Eh, ¿cómo? {insertarnombre} ha vuelto",
    "Me van a tirar la torre...",
    "{insertarnombre} ha participado en los atentados del 11-S",
    "{insertarnombre} quiere jugar al Among Us en la vida real",
    "A {insertarnombre} le gustaría ser un furry",
    "Ojalá {insertarnombre} fuera mi padre",
    "¡Viva {pais}!",
    "{insertarnombre} no era tan malo",
    "Me da igual que la gente se esté matando",
    "Te han matado {nombreuser}, pero tienes 3000 de oro y puedes revivir",
    "Hey, you're finally awake {nombreuser}",
    "¡{pais}!",
    "El poder reside en las matematicas",
]

def generador_frase(nombreuser):
    frase = choice(todasLasFrases)
    if choice(range(25)) == 0:
        frase = frase.replace("{insertarnombre}", nombreuser)

    else:
        frase = frase.replace("{insertarnombre}", choice(nombres))
    
    frase = frase.replace("{nombreuser}", nombreuser)
    frase = frase.replace("{pais}", choice(paises))
    if frase[-1] not in [".", "?", "!"]:
        frase += "."
    
    return frase